name: rapiddown_challenge
description: "A File Downloader App From Pexels"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  provider: ^6.1.1
  path_provider: ^2.1.1
  permission_handler: ^11.4.0
  flutter_dotenv: ^5.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  lottie: ^3.3.1
  google_fonts: ^6.2.1
  open_file_safe_plus: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
